apiVersion: v1
kind: ConfigMap
metadata:
  name: eventuate-cdc-pipeline-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
  SPRING_DATASOURCE_USERNAME: mysqluser
  SPRING_DATASOURCE_PASSWORD: mysqlpw
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
  EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
  EVENTUATELOCAL_CDC_DB_USER_NAME: root
  EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
  EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
  EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
  EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: "1234567890"
  EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
  EVENTUATE_OUTBOX_ID: "1"
