version:               2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: sudo ./install-k8s-tools.sh
      - run: kind create cluster
      - run: ./test-zookeeper.sh          
      - run: ./test-mysql.sh                    
      - run: ./test-kafka.sh                              
      - run: ./test-keycloak.sh                              