apiVersion: v1
metadata:
  name: {{ include "postgres.fullname" . }}-database-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
kind: Secret
data:
  postgresUser: {{ b64enc "eventuate" }}
  postgresPassword: {{ b64enc "eventuate" }}