apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eventuate-cdc.fullname" . }}
  labels:
    {{- include "eventuate-cdc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eventuate-cdc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eventuate-cdc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eventuate-cdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              {{- if .Values.cdc.kafkaBootstrapBrokers }}
              value: {{ .Values.cdc.kafkaBootstrapBrokers }}
              {{- else }}
              value: {{ default "kafka" .Values.cdc.kafka }}:9092
              {{- end }}

            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              {{- if .Values.cdc.zookeeperConnectString }}
              value: {{ .Values.cdc.zookeeperConnectString }}
              {{- else }}
              value: {{ default "zookeeper" .Values.cdc.zookeeper }}:2181
              {{- end }}
              
            - name: JAVA_OPTS
              value: "-Xmx64m"


          {{- range $dbIndex, $databaseServer := .Values.cdc.databaseServers }}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_TYPE
              value: {{ $databaseServer.readerType | default "mysql-binlog" }} 


            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_LEADERSHIPLOCKPATH
              value: /eventuate/cdc/leader/{{ include "eventuate-cdc.fullname" $ }}/{{ $dbIndex }}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEUSERNAME
              {{- with .credentials.username }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
              
            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEPASSWORD
              {{- with .credentials.password }}
                {{- toYaml . | nindent 14 }}
              {{- end }}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_OUTBOXID
              value: "{{ $dbIndex }}"            

            {{ if eq ($databaseServer.readerType | default "mysql-binlog") "mysql-binlog" }}
            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEURL
              value: jdbc:mysql://{{ .host }}:3306/{{ index $databaseServer.databases 0}} # what is the right value here

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_MONITORINGSCHEMA
              value: {{ index $databaseServer.databases 0}}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEDRIVERCLASSNAME
              value: com.mysql.cj.jdbc.Driver

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC
              value: "false"
            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_MYSQLBINLOGCLIENTUNIQUEID
              value: "99{{ $dbIndex }}"
            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_OFFSETSTOREKEY
              value: MySqlBinlog{{ $dbIndex }}
            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_OFFSETSTORAGETOPICNAME
              value: db.history.common


            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_CDCDBUSERNAME
              {{- with .credentials.username }}
                {{- toYaml . | nindent 14 }}
              {{- end }}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_CDCDBPASSWORD
              {{- with .credentials.password }}
                {{- toYaml . | nindent 14 }}
              {{- end }}

            {{ else if eq $databaseServer.readerType "postgres-wal" }}

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEURL
              value: jdbc:postgresql://{{ .host }}/{{ index $databaseServer.databases 0}} # what is the right value here

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_DATASOURCEDRIVERCLASSNAME
              value: org.postgresql.Driver

            - name: EVENTUATE_CDC_READER_R{{ $dbIndex }}_MONITORINGSCHEMA
              value: public


            {{ end }}

          {{- range $databaseIndex, $database := .databases }}
            - name: EVENTUATE_CDC_PIPELINE_PIPELINER{{ $dbIndex }}P{{ $databaseIndex }}_TYPE
              value: eventuate-tram
            - name: EVENTUATE_CDC_PIPELINE_PIPELINER{{ $dbIndex }}P{{ $databaseIndex }}_READER
              value: R{{ $dbIndex }}

            {{ if eq ($databaseServer.readerType | default "mysql-binlog") "mysql-binlog" }}

            - name: EVENTUATE_CDC_PIPELINE_PIPELINER{{ $dbIndex }}P{{ $databaseIndex }}_EVENTUATEDATABASESCHEMA
              value: {{ $database }}

            {{ else if eq $databaseServer.readerType "postgres-wal" }}

            - name: EVENTUATE_CDC_PIPELINE_PIPELINER{{ $dbIndex }}P{{ $databaseIndex }}_EVENTUATEDATABASESCHEMA
              value: public
            {{ end }}

          {{- end }}
  
          {{- end }}
          envFrom:

          {{- range .Values.cdc.envFroms }}
          - configMapRef:
              name: {{ . }}
          {{- end }} 