apiVersion: v1
metadata:
  name: {{ include "mysql.fullname" . }}-database-credentials
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
kind: Secret
data:
  rootPassword: {{ b64enc "rootpassword" }}
  user: {{ b64enc "mysqluser" }}
  password: {{ b64enc "mysqlpw" }}