name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Prepare
      id: prep
      run: |
        echo VERSION=$(./determine-version.sh)
        echo ::set-output name=VERSION::${VERSION}

    - name: Publish charts
      run: ./publish-charts.sh ${{ steps.prep.outputs.VERSION }}

#    - name: Run chart-releaser
#      env:
#        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
