name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0


    - name: Test-ZK
      run: ./test-zookeeper.sh

    - name: Test-mysql
      run: ./test-mysql.sh

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: container-logs
        path: ~/container-logs
        
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Prepare
      id: prep
      run: |
        VERSION=$(./determine-version.sh)
        echo ::set-output name=VERSION::${VERSION}

    - name: Publish charts
      run: |
        echo ${{ steps.prep.outputs.VERSION }}
        ./publish-charts.sh ${{ steps.prep.outputs.VERSION }}

#    - name: Run chart-releaser
#      env:
#        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
